# Generated by Django 2.2.1 on 2019-06-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrow',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='effort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='rep1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='rep2',
            field=models.IntegerField(default=1),
        ),
    ]
