# Generated by Django 2.2.3 on 2019-07-22 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmer',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='timeslot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RelationsSwimGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Group')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Swimmer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
