# Generated by Django 2.2.3 on 2019-08-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190722_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='group',
            name='endtime',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='group',
            name='starttime',
            field=models.CharField(default='', max_length=25),
        ),
    ]
