# Generated by Django 2.2.1 on 2019-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190611_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='totaldistance',
            field=models.IntegerField(default=0),
        ),
    ]
