# Generated by Django 2.2.1 on 2019-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_plan_totaldistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
