# Generated by Django 2.2.1 on 2019-06-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190602_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
