# Generated by Django 2.2.1 on 2019-06-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_plan_saved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='saved_at',
        ),
    ]
