# Generated by Django 2.2.1 on 2019-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_plan_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='swimmer',
            name='group',
            field=models.CharField(default='', max_length=30),
        ),
    ]
