# Generated by Django 2.2.1 on 2019-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190612_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='info',
            field=models.CharField(default='', max_length=828, null=True),
        ),
    ]
