# Generated by Django 2.2.1 on 2019-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190613_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='birthdate',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
