# Generated by Django 2.2.1 on 2019-06-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_plan_planrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanRow',
        ),
    ]
